services:
  backend:
    build:
      context: ./server
    command: gunicorn --config gunicorn_config.py wsgi:app
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "80:4173"
    depends_on:
      - backend
      - storage

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dummy_db
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data_files
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    container_name: storage
    restart: always
    volumes:
      - minio_data:/data
      - ./storage/bucket-policy.json:/bucket-policy.json  # Mount your policy file here
      - ./storage/init-minio.sh:/init-minio.sh  # Mount the init script here
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: unpossible_to_guess_123  # Change this!
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    entrypoint: ["sh", "-c", "chmod +x /init-minio.sh && /init-minio.sh && minio server /data --console-address ':9001'"]

volumes:
  postgres_data:
  minio_data:
