services:
  backend:
    build:
      context: ./server
    command: gunicorn --config gunicorn_config.py wsgi:app
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "80:4173"
    depends_on:
      - backend
      - storage

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dummy_db
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data_files
    ports:
      - "5432:5432"

  storage:
    image: nginx:latest
    container_name: nginx-file-storage
    ports:
      - "9000:9000"
    volumes:
      - storage_data:/usr/share/nginx/html/files
      - ./storage/nginx.conf:/etc/nginx/nginx.conf:ro
    entrypoint: [ "/bin/sh", "-c", "mkdir -p /usr/share/nginx/html/files && exec nginx -g 'daemon off;'" ]
    restart: unless-stopped

volumes:
  postgres_data:
  storage_data:
