services:
  backend:
    build:
      context: ./server
    command: gunicorn --config gunicorn_config.py wsgi:app
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "80:4173"
    depends_on:
      - backend
      - storage

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dummy_db
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data_files
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    container_name: storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  setup-minio:
    image: minio/mc
    depends_on:
      - storage
    volumes:
      - ./storage/:/storage
    entrypoint: ["/bin/sh", "/storage/initialize-buckets.sh"]

volumes:
  postgres_data:
  storage:
