version: '3.8'
services:
  backend:
    command: gunicorn --config /app/gunicorn_config.py wsgi:app
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "3000:4173"
    depends_on:
      - backend

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dummy_db
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data_files
    ports:
      - "5432:5432"

volumes:
  postgres_data:
