name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            # Navigate to project directory (create if it doesn't exist)
            mkdir -p ~/team-project
            cd ~/team-project
            
            # Pull latest changes or clone if doesn't exist
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git .
            fi
            
            # Build and restart containers
            docker-compose down
            docker-compose build
            docker-compose up -d
            
            # Optional: Show logs to verify deployment
            docker-compose logs --tail=20
          EOF