name: Docker Publish

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository name
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/team-project-client:latest
